version: '3'


services:
  nginx:
    container_name: nginx
    build: requirements/nginx/
    depends_on: 
      - wordpress
    ports:
      - 80:80
    restart: unless-stopped
    env_file: .env
    volumes:
      - wordpress:/usr/share/nginx/html
      - wordpress:/var/www/html/
    networks:
      - inception
  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress/
    restart: unless-stopped
    env_file: .env
    ports:
      - 9000:9000
    volumes:
      - wordpress:/var/www/html/
    networks:
      - inception

volumes:
  wordpress:
    driver: local
    driver_opts:
      type : none
      device: ./data/wordpress/
      o: bind
networks:
  inception :
    driver: bridge