version: '3'

services:
  db:
    build: requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    ports:
      - 3306:3306
    volumes: 
      - /home/mait-aad/data/db:/var/lib/mysql
    # command: '--default-authentication-plugin=mysql_native_password'
    # networks:
    #   - app-network
  wordpress:
    depends_on: 
      - mariadb
    build: requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    # ports:
    #   - 9000:9000
    volumes:
      - /home/mait-aad/data/wordpress:/var/www/html
    # networks:
    #   - app-network
  webserver:
    depends_on:
      - wordpress
    build: requirements/nginx
    container_name: webserver
    restart: unless-stopped
    # ports:
    #   - 443:443
    volumes:
      - /home/mait-aad/data/wordpress
    # networks:
    #   - app-network

  # volumes:
  #   certbot-etc:
  #   wordpress:
  #   dbdata:

  # networks:
  #   app-network:
  #     driver: bridge