version: '3'

services:
  mariadb:
    image: mariadb
    build:
      context: requirements/mariadb
    restart: unless-stopped
    env_file: .env
    ports:
      - 3306:3306
    volumes: 
      - /home/mait-aad/data/db:/var/lib/mysql/
    networks:
      - inception
  nginx:
    container_name: nginx
    build: requirements/nginx/
    ports:
      - 8080:443
    restart: unless-stopped
    env_file: .env
    volumes:
      - /home/mait-aad/data/wordpress/:/usr/share/nginx/html
      - /home/mait-aad/data/wordpress/:/var/www/html/
    networks:
      - inception
  wordpress:
    image: wordpress
    build:
      context: requirements/wordpress/
    depends_on: 
      - mariadb
    restart: unless-stopped
    env_file: .env
    ports:
      - 9000:9000
    volumes:
      - /home/mait-aad/data/wordpress/:/var/www/html/
    networks:
      - inception

volumes:
  wordpress:
  db:

networks:
  inception :
    driver: bridge