version: '3'


services:
  mariadb:
    image: mariadb
    build:
      context: requirements/mariadb
    restart: unless-stopped
    env_file: .env
    ports:
      - 3306:3306
    volumes: 
      - db:/var/lib/mysql/
    networks:
      - inception
  nginx:
    container_name: nginx
    build: requirements/nginx/
    depends_on: 
      - wordpress
    ports:
      - 80:80
    restart: unless-stopped
    env_file: .env
    volumes:
      - wordpress:/usr/share/nginx/html
      - wordpress:/var/www/html/
    networks:
      - inception
  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress/
    depends_on: 
      - mariadb
    restart: unless-stopped
    env_file: .env
    ports:
      - 9000:9000
    volumes:
      - wordpress:/var/www/html/
    networks:
      - inception

volumes:
  wordpress:
    driver: local
    driver_opts:
      type : none
      device: ../data/wordpress/
      o: bind
  db:
    driver: local
    driver_opts:
      type : none
      device: ../data/db/
      o: bind
networks:
  inception :
    driver: bridge