FROM debian:buster

RUN apt-get update -y \
	&& apt-get upgrade \
    && apt-get install mariadb-server -y

COPY /tools/create_mariadb_admin_user.sql /var/www/create_mariadb_admin_user.sql
RUN service mysql start && mysql < /var/www/create_mariadb_admin_user.sql && rm -f /var/www/create_mariadb_admin_user.sql;
CMD ["mysqld"]