FROM debian:buster

ENV MYSQL_ADMIN_USER mait-aad


RUN apt-get update -y \
	&& apt-get upgrade -y\
    && apt-get -y install lsb-release apt-transport-https ca-certificates wget \
	&& wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg \
	&& echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/php.list \
	&& apt-get update -y \
    && apt-get install php8.1 php8.1-cli php8.1-mysql php8.1-gd php8.1-xml php8.1-fpm wget -y 
RUN wget https://wordpress.org/latest.tar.gz \
    && tar -xvzf latest.tar.gz \
	&& mkdir -p /var/www/html/ \
	&& mv wordpress /var/www/html/ \
	&& chown -R www-data:www-data /var/www/html/\
	&& mkdir /run/php/ \
	&& touch /run/php/php8.1-fpm.pid
COPY tools/info.php /var/www/html/info.php
COPY tools/wp-config.php /var/www/html/wp-config.php
COPY tools/www.conf /etc/php/8.1/fpm/pool.d/
CMD ["php-fpm8.1","-RF"]