FROM debian:buster

ENV MYSQL_ADMIN_USER mait-aad


RUN apt-get update -y \
	&& apt-get upgrade -y\
    && apt-get -y install lsb-release apt-transport-https ca-certificates wget \
	&& wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg \
	&& echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/php.list \
	&& apt-get update -y \
    && apt-get install php8.1-fpm wget -y \
    && mkdir -p /usr/share/webapps/ \
    && mkdir -p /var/www/localhost/htdocs/wordpress
COPY tools/wp-config.php /var/www/html/
COPY tools/www.conf /etc/php/8.1/fpm/pool.d/www.conf
WORKDIR /usr/share/webapps/
RUN wget https://wordpress.org/latest.tar.gz \
    && tar -xvzf latest.tar.gz \
    && mv wordpress /var/www/html/mait-aad.42.fr \
	&& chown -R www-data:www-data /var/www/html/mait-aad.42.fr/ 
RUN chmod -R 755 /var/www/html/mait-aad.42.fr/\
	&& echo "<?php phpinfo(); ?>" >> /var/www/html/mait-aad.42.fr/index.php \
	&& mkdir /run/php/ \
	&& touch /run/php/php8.1-fpm.pid \
	&& usermod -aG "www-data" "www-data"


CMD ["php-fpm8.1", "-FR"]