FROM debian:buster

RUN apt-get update -y \ 
	&& apt-get upgrade -y \ 
	&& apt-get install -y nginx 
COPY tools/default /etc/nginx/sites-available/default
RUN mkdir -p /var/www/html/\
	&& chown -R www-data:www-data /var/www/html/
CMD ["nginx", "-g" ,"daemon off;"]
