FROM debian:buster

RUN apt-get update -y \ 
	&& apt-get upgrade -y \ 
	&& apt-get install -y nginx 
COPY tools/mait-aad.42.fr.conf /etc/nginx/conf.d/mait-aad.42.fr.conf
RUN nginx -t
CMD ["nginx", "-g" ,"daemon off;"]
